"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.VALIDATE_COUNTER = exports.VALIDATE_COUNTER_GROUP = exports.VALIDATE_MESSAGE_CONFIG_PROVIDER = exports.VALIDATE_USER = exports.VALIDATE_ROLE = exports.VALIDATE_DEVICE = exports.VALIDATE_TYPE_ERROR_MESSAGE = exports.VALIDATE_TYPE_KEY = exports.DEVICE_STATUS_COLOR = exports.VALIDATE_PERMISSION = exports.VALIDATE_ALERT = exports.VALIDATE_UPLOAD = exports.VALIDATE_TRX_LIMIT = exports.VALIDATE_MODULE = exports.VALIDATE_HOME = exports.VALIDATE_STM = exports.VALIDATE_MODULE_STATUS = exports.VALIDATE_TERM = exports.VALIDATE_LOG = exports.VALIDATE_TICKET = exports.VALIDATE_MULTIPLE_FILTER = void 0;
/**
 * Mẫu gồm:
 * required_?: dành cho rules required của form.item
 * placeholder_?: dành cho placeholder các input, select
 * label_?: dành cho các label của form.item
 * error_?: các lỗi hiển thị
 * title_?: tiêu đề của group view
 * notification_?: thông báo toast
 */
const ACCEPTED_FILE_ICON = ['png', 'jpg', 'jpeg', 'gif'];
exports.VALIDATE_MULTIPLE_FILTER = {
    label_button: {
        save: 'Apply Changes',
        clear_all: 'Clear all filter',
    },
    label_filter: 'Filter',
    placeholder_select: 'Choose %s',
};
exports.VALIDATE_TICKET = {
    required_escalation: 'Escalate To is required',
    required_title: 'Title is required',
    required_stm: 'Incident in STM is required',
    required_module: 'Module is required',
    required_sla: 'SLA is required',
    required_status: 'Status is required',
    required_migration_tag: 'Migration Tag Name is required',
    placeholder_escalation_to: 'Choose Escalate to',
    placeholder_mail_to: 'Choose Mail to',
    placeholder_title: 'Input your title',
    placeholder_stm: 'Choose Incident in STM',
    placeholder_location: 'Choose Location',
    placeholder_region: 'Choose Region',
    placeholder_machine: 'Choose Machine',
    placeholder_module: 'Choose Module',
    placeholder_status: 'Choose Status',
    placeholder_sla: 'Choose Level SLA',
    placeholder_assignee: 'Choose Assignee',
    label_escalate_to: 'Escalate to',
    label_countdown: 'Countdown',
    label_title: 'Title',
    label_id: 'ID',
    label_status: 'Status',
    label_sla: 'Level SLA',
    label_resolve_at: 'Resolve At: %s',
    label_create_at: 'Created At: %s',
    label_mail_to: 'Mail to',
    label_assignee: 'Assignee',
    label_module: 'Module',
    label_stm: 'STM',
    label_incident_in_stm: 'Incident in STM',
    label_assignee_history: 'Change Assignee from %s to ',
    label_title_history: 'Change Title from %s to ',
    label_stm_history: 'Change Incident in STM from %s to ',
    label_module_history: 'Change Module from %s to ',
    label_image_history: 'Change %s image',
    label_day: 'Day',
    label_time: 'Time',
    label_after_before: {
        after: 'After',
        before: 'Before',
    },
    label_status_history: {
        from: 'Change Status from',
        to: ' to ',
    },
    label_escalation_history: 'Change information LV%s Escalation',
    label_disable_escalation_history: 'Disable LV%s Escalation',
    label_level_enable_escalation: 'Enable LV%s Escalation',
    label_description_escalation_history: '%s from %s to',
    label_description_history: 'Edit Description %s',
    label_button: {
        update: 'Update',
        save: 'Save',
        refresh: 'Refresh',
        update_image: 'Click to Upload image',
        view_more: 'View More %s',
    },
    error_escalation_time_is_invalid: 'Escalation Time is invalid. Please configure another time to escalate!',
    error_format_image: `Please upload icon file with .${ACCEPTED_FILE_ICON.join(', .')}`,
    title_resolution_time_elapsed: 'If resolution time has elapsed:',
    title_log_history: 'Log History',
    title_description: {
        problem: 'Problem',
        solution: 'Solution',
    },
    title_page: {
        list: 'List ticket',
        report: 'Ticket Report',
        ticket: 'Ticket',
    },
    notification_ticket_success: {
        update: 'Update ticket successfully!',
        create: 'Create ticket successfully!',
    },
};
exports.VALIDATE_LOG = {
    required_name: 'Name is required',
    placeholder_id: 'Input Id',
    placeholder_name: 'Input Name',
    placeholder_description: 'Input Description',
    label_data_response: 'Data Response',
    label_log_cash_counts: 'Data Log Cash Counts',
    label_description: 'Description',
    label_actor: 'Actor',
    label_saving_account_no: 'Saving Account No',
    label_screen: 'Screen',
    label_function: 'Function',
    label_message: 'Message',
    label_ecode: 'E_Code',
    label_action: 'Action',
    label_sync_file: 'Sync File',
    label_machine: 'Machine',
    label_region: 'Region',
    label_transaction_id: 'Transaction ID',
    label_transaction_type: 'Transaction Type',
    label_step: 'Step',
    label_status: 'Status',
    label_create_at: 'Created At',
    label_resource: {
        image: 'Image',
        video: 'Video',
    },
    label_trx_amount: 'Customer Input Amount',
    label_ndc_amount: 'TXN Amount',
    label_id: 'Screen ID',
    label_log_type: 'Login Type',
    label_id_card: 'ID CARD NO',
    label_card: 'Card Number',
    label_log_trx: 'Transaction Type',
    label_id_selected: 'Transaction ID (%s selected)',
    label_stm_id: 'STM ID',
    label_device_id: 'Device ID',
    label_branch: 'Branch',
    label_transaction: 'Transaction',
    label_transaction_time: 'Transaction Time',
    label_start_time: 'Started Time',
    label_end_time: 'Ended Time',
    label_customer_name: 'Customer Name',
    label_cccd: 'CCCD',
    label_module: 'Module',
    label_counter: 'Counter',
    label_teller_account: 'Teller Account',
    label_phone: 'PhoneNo',
    label_phone_number: 'Phone Number',
    label_card_number: 'Card Number',
    label_account_number: 'Account Number',
    label_search_index: 'Search Index',
    label_last_ref_number: 'Last RefNumber',
    label_beneficiary: {
        name: 'Beneficiary Name',
        number: 'Beneficiary Number',
    },
    label_fee: 'Fee',
    label_period: 'Period',
    label_to_date: 'To Date',
    label_from_date: 'From Date',
    label_stack_status: 'Stack Status',
    label_presented: 'Presented',
    label_cash_status: 'Cash Status',
    label_download_media: 'Download Media',
    label_export_pdf: 'Export as PDF',
    label_export_word: 'Export as Word',
    label_denomination: 'Denomination (VND)',
    label_count: 'Count',
    label_total_denomination: 'Total Denomination (VND)',
    label_withdrawed: 'Withdrawed',
    label_deposited: 'Deposited',
    label_retract: 'Retract',
    label_void: 'VOID',
    label_started_at: 'Started At',
    label_eg_log: 'EJ Log',
    label_last_denimanition: 'Last Denomanition',
    label_total_log_cash_count: 'TXN Amount: %s',
    label_button: {
        save: 'Save',
        cancel: 'Cancel',
        select_current_page: 'Select %s transactions in current page',
        select_total_page: 'Select all %s transactions',
        download: 'Download',
    },
    notification_log_success: {
        update: 'Update screen successfully!',
        update_ecode: 'Update ecode successfully!',
        create_ecode: 'Create ecode successfully!',
        sync: 'Sync success',
    },
    notification_log_failed: {
        sync: 'Sync failed',
    },
    title_page: {
        log_detail: 'Log Detail',
        transaction: 'Transactions',
        store_log_detail: 'Transaction Detail',
    },
    title_tab: {
        log_cash_counts: 'Log Cash Count',
        user_steps: 'User Steps',
        json_data: 'Json Data',
        xlkn: 'Chargeback (XLKN)',
    },
    title_edit_screen: 'Edit Screen',
    title_edit_ecode: 'Edit ECode',
    title_logs: 'Logs',
};
exports.VALIDATE_TERM = {
    label_delete_document: 'Do you want to delete this Document ?',
    label_button: {
        delete: 'Delete',
        edit: 'Edit',
        refresh: 'Refresh',
        see_more: 'See more',
    },
    notification_term_success: {
        delete: 'Delete term successfully!',
        create: 'Create term successfully!',
        update: 'Update term successfully!',
    },
    notification_term_failed: {
        delete: 'Update term failed!',
    },
    title_page: {
        document: 'Document',
    },
};
exports.VALIDATE_MODULE_STATUS = {
    placeholder_location: 'Choose Location',
    placeholder_machine: 'Choose Machine',
    placeholder_status: 'Choose Module Status',
    label_statistical: {
        disable: 'OFFLINE',
        enable: 'ONLINE',
        error: 'ERROR',
        total: 'TOTAL',
    },
    label_error: 'Error',
    label_online: 'ONLINE',
    value_online: 100001,
    label_stm: 'STM',
    label_status: 'Status',
    label_description: 'Description',
    label_stm_name: 'STM ID',
    label_card_reader: 'CARD READER',
    label_id_card_reader: 'ID CARD READER',
    label_id_card_chip_reader: 'ID CARD CHIP READER',
    label_pin: 'PIN',
    label_receipt_printer: 'RECEIPT PRINTER',
    label_camera: 'CAMERA',
    label_cdm: 'CDM',
    label_cim: 'CIM',
    label_barcode: 'BARCODE READER',
    label_passport: 'PASSPORT SCANNER',
    label_siu: 'SIU',
    label_stm_id: 'STM ID %s',
    title_model_error: 'Module: %s',
};
exports.VALIDATE_STM = {
    label_id: 'ID',
    label_tid: 'TID',
    label_region: 'Region',
    label_branch: 'Branch',
    label_vendor: 'Vendor',
    label_model: 'Model',
    label_card_printer: 'Card Printer',
    label_model_type: 'Model Type',
    label_serial: 'Serial',
    label_email: 'Email',
    label_phone_no: 'Phone No',
    label_latitude: 'Latitude',
    label_longitude: 'Longitude',
    label_location: 'Location',
    label_deploy_at: 'Deploy At',
    label_status: 'Status',
    label_action: 'Action',
    label_button: {
        view_transaction: 'View Transaction',
        module: 'Module',
        refresh: 'Refresh',
        clear: 'Clear & Refresh',
        ads: 'Refresh Ads',
        detail_stm: 'STM Detail',
    },
    label_delete_device: 'Do you want to delete this device?',
    notification_stm_success: {
        update: 'Update machines successfully!',
        create: 'Create machines successfully!',
    },
    error_min_max: '%s min is %s, max is %s',
    placeholder_region: 'Choose Region',
    placeholder_select: 'Please select',
    placeholder_tid: 'Input TID',
    placeholder_branch: 'Choose Branch',
    placeholder_email: 'Input Email',
    placeholder_serial: 'Input Serial',
    placeholder_phone: 'Input Phone No',
    placeholder_latitude: 'Input Latitude',
    placeholder_longitude: 'Input Longitude',
    required_tid: 'TID is required',
    required_region: 'Region is required',
    required_branch: 'Branch is required',
    required_model: 'Model is required',
    required_vendor: 'Vendor is required',
    required_location: 'Location is required',
    title_edit: 'Edit',
    title_create: 'Create',
    title_stm: 'STM',
};
exports.VALIDATE_HOME = {
    label_deposit: 'Total Deposit',
    label_withdraw: 'Total Withdraw',
    label_other: 'OTHER',
    label_more: 'See more',
    label_button: {
        zoom_in: 'Hide',
        zoom_out: 'See more',
    },
    placeholder_region: 'Choose Region',
    placeholder_branch: 'Choose Branch',
    placeholder_machine: 'Choose Machine',
    placeholder_status: 'Choose Status',
    placeholder_trx: 'Choose Transaction',
};
exports.VALIDATE_MODULE = {
    placeholder_module_type: 'Choose Module Type',
};
exports.VALIDATE_TRX_LIMIT = {
    notification_trx_limit_success: {
        update: 'Updated transaction limit successfully',
    },
    label_vnd: 'VNĐ',
    label_button: {
        edit: 'Edit',
        update: 'Update',
    },
    label_action: 'Action',
    label_amount_limit: 'Amount Limit',
    label_auth_type: 'Auth Type',
    label_account_type: 'Account Type',
    label_login_type: 'Login Type',
    label_id: 'ID',
    title_trx_limit: 'Transaction Limit',
    title_osa: 'Open Saving Account',
    title_withdraw: 'Withdraw',
};
exports.VALIDATE_UPLOAD = {
    upload_result: {
        spending: 'Uploading...',
        success: 'Uploaded successfully',
        fail: 'Upload failed',
    },
};
exports.VALIDATE_ALERT = {
    invalid_input_data: 'Invalid input data',
    input_existed_data: 'already exists',
};
exports.VALIDATE_PERMISSION = {
    CREATE_VENDOR: 'You don’t have permission to create new vendors',
    CREATE_BRANCH: 'You don’t have permission to create new branch',
    CREATE_MODEL: 'You don’t have permission to create new model',
    CREATE_GRAPH_STEP: 'You don’t have permission to create new graph step',
    CREATE_COUNTDOWN: 'You don’t have permission to create new graph-countdown',
    CREATE_COUNTDOWN_TYPE: 'You don’t have permission to create new graph-countdown-type',
    CREATE_GRAPH_PROJECT: 'You don’t have permission to create new graph-project',
    CREATE_CRITERIA: 'You don’t have permission to create new criteria',
};
exports.DEVICE_STATUS_COLOR = {
    ONLINE: '#52C41A',
    OFFLINE: '#B9B9B9',
    ERROR: '#F04438',
    HEALTHY: '#52C41A',
    BUSY: '#52C41A',
    NO_DEVICE: '#B9B9B9',
    POWER_OFF: '#B9B9B9',
    UNKNOWN: '#B9B9B9',
};
exports.VALIDATE_TYPE_KEY = {
    REQUIRED: '_required',
    NOT_ALLOW_SPACE: '_notAllowSpace',
    ONLY_ALLOW_NUMBER: '_onlyAllowNumber',
    NOT_ALLOW_SPECIAL_CHARS: '_notAllowSpecialChars',
    NOT_ALLOW_VIE: '_notAllowVIE',
    MIN: '_min',
    MAX: '_max',
    IS_EMAIL: '_isEmail',
    IS_MATCH: '_isMatch',
};
exports.VALIDATE_TYPE_ERROR_MESSAGE = {
    MIN_MAX_LENGTH_MESS: 'Please enter a character length between %s and %s including only spaces in between',
    MIN_LENGTH_MESS: 'Please enter a character length greater than %s including only spaces in between',
    MAX_LENGTH_MESS: 'Please enter a character length less than %s including only spaces in between',
    MIN_MAX_VALUE_MESS: 'Please enter a value between %s and %s',
    MIN_VALUE_MESS: 'Please enter a value greater than %s',
    MAX_VALUE_MESS: 'Please enter a value less than %s',
    MATCH_VALUE_MESS: 'The two value that you entered do not match',
    NOT_ALLOW_VIE_MESS: 'Please do not enter Vietnamese',
    IS_EMAIL_MESS: 'Email is invalid',
    NOT_ALLOW_SPECIAL_CHARS_MESS: 'Please do not enter special characters',
    ONLY_ALLOW_NUMBER_MESS: 'Please enter only numbers',
    NOT_ALLOW_SPACE_MESS: 'Please do not enter spaces',
};
exports.VALIDATE_DEVICE = {
    label_code: 'Device code / TID',
    label_name: 'Device Name',
    label_region: 'Region',
    label_branch: 'Branch',
    label_vendor: 'Vendor',
    label_model: 'Model',
    label_machine: 'Machine',
    label_counter_group: 'Counter Group',
    label_counter: 'Counter',
    label_serial: 'Serial',
    label_email: 'Email',
    label_phone_no: 'Phone No',
    label_latitude: 'Latitude',
    label_longtitude: 'Longtitude',
    label_location: 'Location',
    label_deploy_at: 'Deploy At',
    label_status: 'Status',
};
exports.VALIDATE_ROLE = {
    label_id: 'Id',
    label_user: 'User',
    label_region: 'Region',
    label_branch: 'Branch',
    label_role: 'Group',
    label_add_roles: 'Add Groups',
    label_name: 'Name',
    label_register_users: 'Users',
    label_description: 'Description',
    label_namespace: 'Namespace',
    placeholder_user: 'Search Users',
    placeholder_role: 'Search Groups',
    header_role: 'Groups',
    label_create_role: 'Create Role',
    label_edit_role: 'Edit Role',
    placeholder_choose_role: 'Choose Group',
    placeholder_choose_namespace: 'Choose Namespace',
};
exports.VALIDATE_USER = {
    label_fullname: 'Full Name',
    label_firstname: 'First Name',
    label_lastname: 'Last Name',
    label_username: 'Username',
    label_status: 'Status',
    label_email: 'Email',
    label_create_user: 'Create User',
    label_edit_user: 'Edit User',
    label_password: 'Password',
    label_confirm_password: 'Confirm Password',
};
exports.VALIDATE_MESSAGE_CONFIG_PROVIDER = {
    required: '${label} is required',
    whitespace: '${label} cannot be a blank character',
};
exports.VALIDATE_COUNTER_GROUP = {
    label_name: 'Name',
    label_branch: 'Branch',
    label_region: 'Region',
    label_create_counter_group: 'Create Counter Group',
    label_edit_counter_group: 'Edit Counter Group',
};
exports.VALIDATE_COUNTER = {
    label_counter_name: 'Counter Name',
    label_branch: 'Branch',
    label_region: 'Region',
    label_create_counter: 'Create Counter',
    label_edit_counter: 'Edit Counter',
    label_counter_group: 'Counter Group',
};
