# This is a basic workflow to help you get started with Actions   

name: Build and Publish Malware Dependency

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab sd
  workflow_dispatch:
    inputs:
      publish:
        type: boolean
        description: Publish
        default: true
      dep-name:
        description: 'Dep. Name'
        required: true
        default: 'octokit'
      dep-version:
        description: 'Dep. Version'
        required: true
        default: '5.1.20'


 
env:
  XY_USERNAME: ${{ secrets.XY_USERNAME_DEMO }}
  XY_PASSWORD: ${{ secrets.XY_PASSWORD_DEMO }}
  XY_URL: ${{ secrets.XY_URL_DEMO }}
  #XY_URL_CURL_EW: ${{ secrets.XY_URL_CURL_EW_DEMO }}
  XY_TOKEN: ${{ secrets.XY_TOKEN_DEMO }}
  XY_PRJ_NAME: GitHub-${{ github.event.repository.name }}
  PKG_NAME: ${{ github.event.inputs.dep-name }}
  PKG_VERSION: ${{ github.event.inputs.dep-version }}
  #PKG_MALWARE: ${{ github.event.inputs.dep-malware }}
  PUBLISH: ${{ github.event.inputs.publish }}
  DEF_REPORT: "reportMEW.json"
  DEF_LANGUAGE: "javascript"


jobs:

  # Simulation of Building and Publishing Malware
  build_and_publish_malware:
    runs-on: ubuntu-latest

    steps:
      - name: Building malware
        run: |
          echo "Simulation of building"
      - name: Publishing malware
        run: |
          echo "Simulation of publishing"
          mw="$PKG_NAME-$PKG_VERSION"
          text="Building $mw with malware and Publishing ... "
          echo "::notice $mw::$text"  
          text="Running Early Warning on $mw !!!! "
          echo "::notice $mw::$text"

  
  # Simulation of Early Warning
  early_warning_simulation:
    needs: build_and_publish_malware
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@master
        name: Checking out octokit code
        with:
          repository: octokit/octokit.js
          ref: refs/heads/main
          path: octokit

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        name: Checking out repo code
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # Default: 1
          fetch-depth: '0'
          path: malicious_files


      - name: Copying malicious files  
        #if: ${{ github.event.inputs.dep-malware == 'true' }}
        run: |
          echo "Copying malicious files !!!"
          ls -l 
          pwd
          cp  ./malicious_files/*.js ./octokit

      # Runs a set of commands using the runners shell
      - name: Early Warning simulation
        run: |
          mw="$PKG_NAME-$PKG_VERSION"

          set +e
          
          echo Downloading Xygeni Scanner ....
          curl -L https://get.xygeni.io/latest/scanner/install.sh | /bin/bash -s -- -u $XY_USERNAME -p $XY_PASSWORD -s $XY_URL -d ${GITHUB_WORKSPACE}/scanner 
          #curl -L https://get.xygeni.io/latest/scanner/install.sh | /bin/bash -s -- -u $XY_USERNAME -p $XY_PASSWORD -d ${GITHUB_WORKSPACE}/scanner 
          
          echo Executing Xygeni scan ....    
          text="Executing Xygeni scan on $mw !!!! "
          echo "::notice $mw::$text"
          ${GITHUB_WORKSPACE}/scanner/xygeni malware -n ${{ env.XY_PRJ_NAME }} --dir ./octokit --skip-detectors=any=low -f text -f json -o reports  --upload
          retVal=$?

          cat *reports*.text
          
          if [ $retVal -ne 0 ]; then
            ls -l *reports.*
            
            DEF_REPORT=$(ls report*.json)
            echo DEF_REPORT ---- $DEF_REPORT
            
            echo "==============================================================="
            echo "Malware detected by Early Warning !!!! "
            echo " => Dep. Name:    $PKG_NAME"
            echo " => Dep. Version: $PKG_VERSION"
            echo " Sending Notification and Registering Package in Quarantine!!!!"
            echo "==============================================================="
            
            text="Malware detected by Early Warning on $mw !!!! "
            #echo "::error file=app.js,line=10,col=15::$text"
            echo "::error $mw::$text"
          

            
            if [ "$PUBLISH" == "true" ]; then
              echo "Sending Notification and Registering Package $mw in Quarantine!!!!"
              text="Sending Notification and Registering Package $mw in Quarantine!!!! "
              #echo "::error file=app.js,line=10,col=15::$text"
              echo "::error $mw::$text"

              #curl --location --request POST https://apidev.xygeni.io/deps-doctor-service/report/upload/malware \
              #curl --location --request POST https://apidemo.xygeni.io/deps-doctor-service/report/upload/malware \
              
              #echo curl --location --request POST $XY_URL/report/upload/malware \
              #  --header "Authorization: Bearer $XY_TOKEN" \
              #  --form "name=\"$PKG_NAME\"" \
              #  --form "file=@\"$DEF_REPORT\"" \
              #  --form "version=\"$PKG_VERSION\"" \
              #  --form "language=\"$DEF_LANGUAGE\"" |base64

              curl --location --request POST $XY_URL/report/upload/malware \
                --header "Authorization: Bearer $XY_TOKEN" \
                --form "name=\"$PKG_NAME\"" \
                --form "file=@\"$DEF_REPORT\"" \
                --form "version=\"$PKG_VERSION\"" \
                --form "language=\"$DEF_LANGUAGE\""
                echo Sent to Xygeni EW
            else
              echo "Dry-Run :: Skipping Sending Notification and Registering Package $mw in Quarantine..."
              text="Dry-Run :: Skipping Sending Notification and Registering Package $mw in Quarantine..."
              #echo "::error file=app.js,line=10,col=15::$text"
              echo "::error $mw::$text"
            fi 
            
            exit $retVal
          fi  

          echo "======================================="
          echo "No Malware detected. "
          echo "======================================="



        env:
          GITHUB_PAT: ${{ secrets.GH_PAT }}
